# Generated by Django 4.1.10 on 2023-08-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='accent_color',
            field=models.ManyToManyField(related_name='accent_color', to='palette.color'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='dominant_color',
            field=models.ManyToManyField(related_name='dominant_color', to='palette.color'),
        ),
    ]
