# Generated by Django 4.1.10 on 2023-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0003_alter_palette_name_favoritepalette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='accent_color',
            field=models.ManyToManyField(related_name='a_color', to='palette.color'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='dominant_color',
            field=models.ManyToManyField(related_name='d_color', to='palette.color'),
        ),
    ]
